---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: postgres
spec:
  replicas: 1
  triggers: {}
  strategy:
    type: Rolling
  paused: false
  revisionHistoryLimit: 10
  minReadySeconds: 0
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: docker.io/library/postgres:latest
        imagePullPolicy: Always
        name: postgres
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-init-secret
                key: postgres_password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-init-secret
                key: postgres_db_name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-init-secret
                key: postgres_user_name
          - name: POSTGRES_APP_DB
            valueFrom:
              secretKeyRef:
                name: postgres-init-secret
                key: postgres_app_db
          - name: POSTGRES_APP_USER
            valueFrom:
              secretKeyRef:
                name: postgres-init-secret
                key: postgres_app_user
          - name: POSTGRES_APP_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-init-secret
                key: postgres_app_user_password
          - name: PGDATA
            value: "/var/lib/postgresql/data"
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-data-volume
          - mountPath: "/docker-entrypoint-initdb.d/postgres-init-db.sh"
            subPath: postgres-init-db.sh
            name: postgres-init-config
        ports:
        - containerPort: 5432
          protocol: TCP
        - containerPort: 5433
          protocol: TCP
        resources: {}
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-data-claim
        - name: postgres-init-config
          configMap:
            name: postgres-init-config
            items:
            - key: postgres-init-db.sh
              path: postgres-init-db.sh
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30