apiVersion: v1
kind: ConfigMap
metadata:
  name: hadolint-config

data:
  hadolint.yaml: |
    ignored:
      - DL3000
      - SC1010

    trustedRegistries:
      - docker.io
      - registry.apps.kubernetes.local
      - docker-registry.default.svc:5000

