apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonarqube.fullname" . }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    {{- include "sonarqube.selectorLabels" . | nindent 4 }}
