FROM docker.io/jenkins/jnlp-slave

LABEL maintainer=mcaimi@redhat.com
LABEL agent=jenkins-slave-maven

ENV DOCKERVERSION=19.03.5
USER root

RUN curl -o docker-${DOCKERVERSION}.tgz https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKERVERSION}.tgz \
  && tar xzvf docker-${DOCKERVERSION}.tgz --strip=1 -C /usr/local/bin/ docker/docker \
  && rm docker-${DOCKERVERSION}.tgz \
  && curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl \
  && chmod +x ./kubectl && mv ./kubectl /usr/local/bin/kubectl

