apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: base-openjdk
spec:
  imagePullPolicy: IfNotPresent
  tags:
  - annotations:
      openshift.io/display-name: base-openjdk
      openshift.io/imported-from: quay.io/quarkus/centos-quarkus-native-s2i:latest
    from:
      kind: DockerImage
      name: 'quay.io/quarkus/centos-quarkus-native-s2i:latest'
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: java-runner
spec:
  tags:
  - name: latest
---

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "java-runner"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "java-runner:latest"
  source:
    git:
      uri: https://github.com/mcaimi/k8s-demo-app.git
      ref: "vmware-thin"
#    sourceSecret:
#      name: "buildbot-auth"
    contextDir: "containers/java-runner"
  images:
  - from:
      kind: "ImageStreamTag"
      name: "base-openjdk:latest"
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      buildArgs:
        - name: "nexus_repo_url"
          value: "nexus.apps.kubernetes.local"
        - name: "artifact_name"
          value: "org.redhat:openshift-demo-application-quarkus-runner:1.1.1-SNAPSHOT"
        - name: "nexus_auth"
          value: "jenkins:jenkins"
      noCache: true
      from:
        kind: "ImageStreamTag"
        name: "base-openjdk:latest"
  triggers:
    - type: "ImageChange"
    - type: "ConfigChange"

