apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: jenkins-slave
spec:
  imagePullPolicy: IfNotPresent
  tags:
  - annotations:
      openshift.io/display-name: jenkins-slave
      openshift.io/imported-from: docker.io/jenkins/slave:latest
    from:
      kind: DockerImage
      name: 'docker.io/jenkins/slave:latest'
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: maven-agent
spec:
  tags:
  - name: latest
---

apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: "jenkins-maven-agent"
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "maven-agent:latest"
  source:
    git:
      uri: https://github.com/mcaimi/k8s-demo-app.git
      ref: "master"
#    sourceSecret:
#      name: "buildbot-auth"
    contextDir: "containers/maven-agent"
  images:
  - from:
      kind: "ImageStreamTag"
      name: "maven-agent:latest"
  runPolicy: "Serial"
  strategy:
    dockerStrategy:
      noCache: true
      from:
        kind: "ImageStreamTag"
        name: "jenkins-slave:latest"
  triggers:
    - type: "ImageChange"
    - type: "ConfigChange"

