bases:
  - ../pgcommon
namespace: NS_ID
namePrefix: NS_ID-
nameSuffix: "-BUILD_ID"
commonLabels:
  app: k8s-demo-app
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "noprod"
patchesStrategicMerge:
- mem-sizing.yaml
images:
- name: postgres
  newName: docker.io/library/postgres
  newTag: latest
secretGenerator:
- name: postgres-init-secret
  literals:
  - postgres_password=P0stgr3s
  - postgres_db_name=pgdev_preprod
  - postgres_user_name=pgpreprod
  - postgres_app_user=preprod_user
  - postgres_app_db=preprod_db
  - postgres_app_user_password=hibernate
configMapGenerator:
- name: postgres-init-config
  files:
    - postgres-init-db.sh