bases:
  - ../common
namespace: prod
namePrefix: prod-
nameSuffix: "-latest"
commonLabels:
  app: k8s-quarkus-prod
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "prod"
patchesStrategicMerge:
- ingress-route.yaml
patchesJson6902:
- path: mem-sizing.yaml
  target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: java-runner
secretGenerator:
- name: quarkus-init-secret
  literals:
  - postgres_app_user=prod_user
  - postgres_app_db=prod_db
  - postgres_app_user_password=hibernate
  - db_driver=postgresql
  - db_hostname=prod-postgres-service-latest
  - db_port=5432
  - orm_log=true
  - default_schema=prod_schema
  - db_generation=none
  - hibernate_load_file=no-file
  - jdbc_max_size=8
  - jdbc_min_size=2
  - flyway_migrate_at_start=true
  - flyway_baseline_version=1.0.0
  - flyway_baseline_description=Prod_Initial
  - flyway_connection_retries=300
  - flyway_migration_table=prod_history
  - flyway_migrations_location=db/migrations/prod
  - flyway_baseline_on_migrate=false
images:
- name: java-runner
  newName: docker-registry.default.svc:5000/prod/java-runner
  newTag: prod