bases:
  - ../pgcommon
namespace: preprod
namePrefix: preprod-
nameSuffix: "-001"
commonLabels:
  app: k8s-demo-app
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "noprod"
patchesStrategicMerge:
- mem-sizing.yaml
images:
- name: postgres
  newName: docker.io/library/postgres
  newTag: latest
secretGenerator:
- name: postgres-init-secret
  literals:
  - postgres_password=P0stgr3s
  - postgres_db_name=pgdev_preprod
  - postgres_user_name=pgpreprod
