bases:
  - ../common
namespace: dev
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: k8s-demo-app
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "noprod"
patchesStrategicMerge:
- mem-sizing.yaml
- ingress-route.yaml
images:
- name: java-runner
  newName: registry.apps.kubernetes.local/java-runner
  newTag: dev