apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/openshift-jenkins-operator.jenkins: ""
  managedFields:
  name: openshift-jenkins-operator
  # namespace: jenkins
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: openshift-jenkins-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: jenkins-operator.0.7.1


