---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-runner-servicemonitor
  namespace: jenkins
  labels:
    app: java-runner
spec:
  endpoints:
  - interval: 5s
    path: /q/metrics
    port: 80-tcp
    scheme: http
  selector:
    matchLabels:
      app: java-runner

