bases:
  - ../common
namespace: prod
namePrefix: production-
nameSuffix: "-latest"
commonLabels:
  app: k8s-quarkus-app
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "prod"
patchesStrategicMerge:
- mem-sizing.yaml
- ingress-route.yaml
secretGenerator:
- name: quarkus-init-secret
  literals:
  - postgres_app_user=prod_user
  - postgres_app_db=prod_db
  - postgres_app_user_password=hibernate
  - db_driver=postgresql
  - db_hostname=production-postgres-service-latest
  - db_port=5432
  - orm_log=true
  - default_schema=prod_schema
  - db_generation=none
  - hibernate_load_file=no-file
  - jdbc_max_size=8
  - jdbc_min_size=2
  - flyway_migrate_at_start=true
  - flyway_baseline_version=1.0.0
  - flyway_baseline_description=Prod_Initial
  - flyway_connection_retries=300
  - flyway_migration_table=preprod_history
  - flyway_migrations_location=db/migrations/prod
  - flyway_baseline_on_migrate=false
images:
- name: java-runner
  newName: registry.apps.kubernetes.local/java-runner
  newTag: prod