apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: registry
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: ocp-day2
  source:
    path: 02-registry/
    repoURL: >-
      ssh://git@gitlab.consulting.redhat.com:2222/gps-laboratory/k8s-resources.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true 
