bases:
  - ../pgcommon
namespace: prod
namePrefix: prod-
nameSuffix: "-latest"
commonLabels:
  app: k8s-postgres-prod
commonAnnotations:
  deployedBy: "jenkins"
  chain: "devops-pipeline"
  environment: "prod"
patchesStrategicMerge:
- storageclass.yaml
- mem-sizing.yaml
images:
- name: postgres
  newName: docker.io/library/postgres
  newTag: latest
secretGenerator:
- name: postgres-init-secret
  literals:
  - postgres_password=P0stgr3s
  - postgres_db_name=pg_prod
  - postgres_user_name=pgprod
  - postgres_app_user=prod_user
  - postgres_app_db=prod_db
  - postgres_app_user_password=hibernate
configMapGenerator:
- name: postgres-init-config
  files:
    - postgres-init-db.sh
